WebClientBundle_homepage:
    pattern:  /
    defaults: { _controller: WebClientBundle:Default:index }

WebClientBundle_login:
    pattern:  /login
    defaults: { _controller: WebClientBundle:Default:log }

_login_check:
    pattern:  /login_check

_logout:
    pattern:  /logout