<?php

define('EVENT_ID', 1);

define('STATUS_CONFIRMED', 1);
define('STATUS_ACCEPTED', 1);
define('STATUS_TENTATIVE', 2);
define('STATUS_DECLINED', 3);
define('STATUS_CANCELLED', 3);
define('STATUS_UNANSWERED', 4);
define('STATUS_DELEGATED', 5);

define('ALARM_ALERT', 1);
define('ALARM_MAIL', 2);
define('ALARM_SMS', 3);

define('TRANSP_OPAQUE', 0);
define('TRANSP_TRANSPARENT', 1);

define('CLASS_PUBLIC', 1);
define('CLASS_PRIVATE', 2);
define('CLASS_CONFIDENTIAL', 3);

define('ICAL_ACTION_IMPORT', 1);
define('ICAL_ACTION_UPDATE', 2);
define('ICAL_ACTION_DELETE', 3);
define('ICAL_ACTION_NONE', 4);
define('ICAL_ACTION_REPLY', 5);
define('ICAL_ACTION_SUGGESTION', 6);
define('ICAL_ACTION_IMPORT_REQUIRED', 7);
define('ICAL_ACTION_ORGANIZER_UPDATE', 8);
define('ICAL_ACTION_ORGANIZER_NONE', 9);
define('ICAL_ACTION_IMPORT_FROM_PERMISSION', 10);
define('ICAL_ACTION_NONE_FROM_PERMISSION', 11);

define('ATTENDEE_ACL_ORGANIZATION', 'o');
define('ATTENDEE_ACL_WRITE', 'w');
define('ATTENDEE_ACL_PARTICIPATION_REQUIRED', 'p');
define('ATTENDEE_ACL_INVITE_GUESTES', 'i');
define('ATTENDEE_ACL_READ', 'r');

define('CALENDAR_PRIVATE', 0);
define('CALENDAR_PUBLIC', 1);

define('CALENDAR_ACL_WRITE', 'w');
define('CALENDAR_ACL_READ', 'r');
define('CALENDAR_ACL_REMOVE', 'd');
define('CALENDAR_ACL_BUSY', 'b');
define('CALENDAR_ACL_SHARED', 's');
define('CALENDAR_ACL_REQUIRED', 'p');
?>
