# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

ExpressoBundle:
        resource: "@ExpressoBundle/Resources/config/routing.yml"
        prefix:   /
